### ISSUE TITLE
port documentation to roxygen

### ISSUE THREAD

**Issue by dseynaev** [sbihorel/rclipboard#1]
Hi,

Thank you for writing this neat wrapper
would it be possible to add roxygen comments to your source files?
(or commit them if they exist already)

**Comment by sbihorel** [comment]
Thank for your kinds words

First of all, let me tell you that I am not familiar with the use/syntax of roxygen. My understanding is that roxygen facilitates the creation of documentation or Rd files. I am showing my age here, but I am still doing things the old fashion way by writing my Rd files separately. These Rd files exist in the package and documentation (?...) should be available from the R console upon built and installation of the package.

Do you have an additional rationale besides documentation for your request?

I am open to teaching myself about roxygen, but given my limited available time, I will need a pretty strong reason for this.

**Comment by dseynaev** [comment]
Hi

Your understanding of roxygen is largely correct. However, besides making it easier, there is some (arguably subjective) reasoning for using roxygen over handwritten Rd files:
https://cran.r-project.org/web/packages/roxygen2/vignettes/roxygen2.html.
Personally, I think having documentation adjacent to code leads to more well-designed functions and appreciate that the NAMESPACE is being dealt with automatically, increasing maintainability.

My reason for asking is that I am using your package in a project and would like to submit a few small improvements based on my experience with other custom shiny widgets.

If this is of any help, I can write roxygen comments that produce .Rd files nearly identical to the current ones.

**Comment by sbihorel** [comment]
Hi,

I would gladly appreciate any contribution, including the roxygen comments.
One thing I vaguely remember about roxygen is that one has to put a big block of comments at the top of the function. I personally strongly dislike this because of the extra scrolling down that is required to view actual code every time I open my functions... but let's see

**Comment by sbihorel** [comment]
Closing
