### ISSUE TITLE
Using RClipboard / Framework without button

### ISSUE THREAD

**Issue by BerndMaier** [sbihorel/rclipboard#14]
Hi, 
thanks for this nice package. 

I have a question regarding the framework. 

I realized i can't use clipr on a shiny server to set the clipboard client side - so i found rclipboard.

I just wondered if there may be a function or a way to just put stuff into the clipboard, without the rclipButton itself in the ui - when using e.g. another button, and just use it like the clipr::write_clip("string here") function.

As I have a normal action button with some underlying processing, not just plain text, that in the end should write a string into the users clipboard. 

____

Hope this makes sense for an example

observeEvent(input$Name_Check, {
  if (Your_Name = "John") {
    clipr::write_clip("John")
  } else {clipr::write_clip("Not_John")}
})

___

Thank you very much

**Comment by sbihorel** [comment]
Hi

I don't think this particular case should be handle by rclipboard. You probably want to use the `document.execCommand('copy')` by directly calling jasvscript function from your shiny app. See info [here](https://stackoverflow.com/questions/400212/how-do-i-copy-to-the-clipboard-in-javascript) and [here](https://shiny.rstudio.com/articles/communicating-with-js.html).
