### ISSUE TITLE
rclipboard does not work in docker container after version 0.1.4

### ISSUE THREAD

**Issue by can-taslicukur** [sbihorel/rclipboard#15]
Hi, I am using rclipboard in one of my shiny apps which i build using docker. However since updating the package, I get error where the button should be. It works on my mac locally but when i use docker to build my shiny app, there is an error where clipboard button should be. I fixed this by rolling the package's version back to 0.1.3 but I wanted you to be aware of this issue. I think its more of an issue related to Linux OS that the docker image is using instead of docker itself.

The base image that i use for my docker build is [rocker/shiny:4.1.1](https://hub.docker.com/layers/rocker/shiny/4.1.1/images/sha256-1c3f484127cae933cd33c4fdfef67757bf0fd9df25c463c835b13f1a72691cdf?context=explore)

**Comment by sbihorel** [comment]
Hi,
Did you check the content of the shiny log when your app failed with the new version of rclipboard? If so, can you please share it? There is not much I can and will do without the actual error.
The package passed all build checks on linux, windows, and Mac (the arm check is still pending), so it seems like the issue is specific to your workflow.

**Comment by sbihorel** [comment]
I can't say I have used Docker to build Shiny apps in the past but looking at the link you sent, I could not help but notice that your CRAN environment variable seems to target a time stamp of package manager that predates the release of rclipboard 1.0.4...
```
ENV CRAN=https://packagemanager.rstudio.com/cran/__linux__/focal/2021-10-29
```

Could you try to update this path and recompile with the new version of rclipboard?

**Comment by can-taslicukur** [comment]
Hi thank you for answering. I'have recreated the example app on readme with docker to investigate the issue. And there were no errors. You are right the issue is likely specific to my workflow. I will close this issue now. I am sorry for creating a false alarm

App.R 
```
library(rclipboard)
library(shiny)

# The UI
ui <- bootstrapPage(

  rclipboardSetup(),

  # Add a text input
  textInput("copytext", "Copy this:", "Zlika!"),

  # UI ouputs for the copy-to-clipboard buttons
  uiOutput("clip"),

  # A text input for testing the clipboard content.
  textInput("paste", "Paste here:")

)

# The server
server <- function(input, output) {

  # Add clipboard buttons
  output$clip <- renderUI({
    rclipButton(
      inputId = "clipbtn",
      label = "rclipButton Copy",
      clipText = input$copytext,
      icon = icon("clipboard")
    )
  })
}

shinyApp(ui = ui, server = server)
```

Dockerfile
```
# Base image https://hub.docker.com/u/rocker/
FROM rocker/shiny:4.1.1

COPY app.R ./app.R
COPY renv.lock ./renv.lock

RUN Rscript -e 'install.packages("renv")'
RUN Rscript -e 'renv::consent(provided = TRUE)'
RUN Rscript -e 'renv::restore()'

# expose port
EXPOSE 3838

# run app on container start
CMD ["R","-e", "shiny::runApp('app.R', host = '0.0.0.0', port = 3838)"]
```
