### ISSUE TITLE
Help file example app throws error

### ISSUE THREAD

**Issue by mf-rug** [sbihorel/rclipboard#17]
This little example app in the help of `rclipButton`:
```
## Not run
## Not run: 
library(rclipboard)
library(shiny)

# The UI
ui <- bootstrapPage(
  
  rclipboardSetup(),
  
  # Add a text input
  textInput("copytext", "Copy this:", "Zlika!"),

  # UI ouputs for the copy-to-clipboard buttons
  uiOutput("clip"),
  
  # A text input for testing the clipboard content.
  textInput("paste", "Paste here:")
  
)

# The server
server <- function(input, output) {

  # Add clipboard buttons
  output$clip <- renderUI({
    rclipButton("clipbtn", "rclipButton Copy", input$copytext, icon("clipboard"))
  })
  
}

shinyApp(ui = ui, server = server)

## End(Not run)
```

throws this error
Warning: Error in ifelse: 'list' object cannot be coerced to type 'logical'

Apparently it is using the `icon()` as the `modal = ` argument, so to fix it, change 
` rclipButton("clipbtn", "rclipButton Copy", input$copytext, icon("clipboard"))` 
to 
`rclipButton("clipbtn", "rclipButton Copy", input$copytext, modal = FALSE, icon("clipboard"))`

**Comment by sbihorel** [comment]
Thanks for reporting this error. The model argument has not per se needed, but all arguments from the rclipButton must be named.
The code is corrected in github and a revised package version will be on CRAN shortly.
