### ISSUE TITLE
latest rclipboard (version 0.2.0) installation from CRAN failed

### ISSUE THREAD

**Issue by yli110-stat697** [sbihorel/rclipboard#21]
Hi,

When I tried to install the latest (v0.2.0) version of rclipboard from CRAN, there's a failure with the message `object ‘tooltip’ is not exported by 'namespace:bslib'`

I'm on `bslib` 0.4.2 and it seems that **bslib** introduced tooltip() in 0.5.1
https://github.com/rstudio/bslib/blob/main/NEWS.md#new-features-1

Please consider add version requirement of bslib in your DESCRIPTION file https://github.com/sbihorel/rclipboard/blob/c0578c266380c973c0594521cbfb0b49a8cd94d7/DESCRIPTION#L17

**Comment by sbihorel** [comment]
Thanks for the notification
DESCRIPTION file is now updated in version 0.2.1 being pushed on CRAN.
