### ISSUE TITLE
Problem calling rclipButton inside a modal

### ISSUE THREAD

**Issue by shinyquant** [sbihorel/rclipboard#3]
Hi,

first of all: your sample code works perfectly well. Now I want to call `rclipButton()` inside a modal, so I modified your sample code:
```
library(shiny)
library(rclipboard)

ui <- bootstrapPage(  
  rclipboardSetup()
)
server <- function(input, output) {  
  showModal(modalDialog(
    # rclipboardSetup(),
    textInput("copytext", "Copy this:", "Zlika!"),
    uiOutput("clip"),    
    textInput("paste", "Paste here:")    
  ))
  output$clip <- renderUI({
    rclipButton("clipbtn", "rclipButton Copy", input$copytext, icon("clipboard"))
  })
}

shinyApp(ui = ui, server = server)
```
Althought the button shows up, it doesn't copy the copytext to the clipboard.
As you can see I also tried to put `rclipboardSetup()` inside the `modalDialog`, but this doesn't help.

**Comment by sbihorel** [comment]
Hi,

Your code works in my system (see below). After clicking on the copy button, I can paste (Ctrl+V) anywhere including in the model window.

Linux Mint 18.1 Serena 
Rstudio version  1.1.383 
```

> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Linux Mint 18.1

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rclipboard_0.1 shiny_1.0.3   

loaded via a namespace (and not attached):
 [1] compiler_3.4.3  R6_2.2.2        htmltools_0.3.6 tools_3.4.3     yaml_2.1.14     Rcpp_0.12.11    jsonlite_1.5    digest_0.6.12  
 [9] xtable_1.8-2    httpuv_1.3.5    mime_0.5   
```

**Comment by shinyquant** [comment]
I tried it at two different computers (both Windows 7 with different R, RStudio and shiny versions). Both times pasting (Ctrl+V) pastes nothing - but only if the `rclipButton` is inside the modal. If I remove the `showModal(modalDialog(` part everything works as it should.

RStudio 0.99.903
```
> sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                    LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rclipboard_0.1 shiny_1.0.0   

loaded via a namespace (and not attached):
[1] R6_2.2.0        htmltools_0.3.5 tools_3.3.1     Rcpp_0.12.9     digest_0.6.12   xtable_1.8-2    httpuv_1.3.3    mime_0.5       
```

**Comment by sbihorel** [comment]
I unfortunately don't have access to a large variety of systems for testing. Your original code works on both my linux and windows 10 machines. Both are kept fairly updated and have close to the newest versions of RStudio, R, and packages.

It used to be that the rclipButton would not work when running the app in a Rstudio window, users had use the launch.browser=TRUE option or run their apps remotely through a Shiny server. The underlying problem is the ability of your system to support HTML5 execCommand() API. I am actually surprised to  see it working for me when running the app from Rstudio... They must have updated something recently.

Did you try running the app with launch.browser=TRUE?

If that does not work, I would suggest to update your systems if that is possible. Otherwise, there is a very similar package which uses a flash-based architecture (https://github.com/smbache/zeroclipr), you may want to try it.

**Comment by sbihorel** [comment]
> RStudio 0.99.903

This may be your problem. Rtsudio >1.0 has introduced quite a bit a new supported functionality. I would start by updating RStudio.

**Comment by shinyquant** [comment]
> Rtsudio >1.0 has introduced quite a bit a new supported functionality. I would start by updating RStudio.

I actually tried it at home (Windows 7) with the newest versions of RStudio, R and shiny and it didn't work. Also I ran the apps through a Shiny server, which didn't help either.
> Did you try running the app with launch.browser=TRUE?

Yes I did, but still no success.
I don't understand why the button works outside the `modal`-environment but not inside.

>If that does not work, I would suggest to update your systems if that is possible. Otherwise, there is a very similar package which uses a flash-based architecture (https://github.com/smbache/zeroclipr), you may want to try it.

Unfortunately due to company security policies, I can't install packages via devtools. But I will try installing zeroclipr on my computer at home.

**Comment by shinyquant** [comment]
> If that does not work, I would suggest to update your systems if that is possible. Otherwise, there is a very similar package which uses a flash-based architecture (https://github.com/smbache/zeroclipr), you may want to try it.

But I will try installing zeroclipr on my computer at home.

**Comment by shinyquant** [comment]
> If that does not work, I would suggest to update your systems if that is possible. Otherwise, there is a very similar package which uses a flash-based architecture (https://github.com/smbache/zeroclipr), you may want to try it.

zeroclipr worked for me. Thanks for the hint.

**Comment by oganm** [comment]
On an ubuntu machine running shiny server I was unable to make this work. Didn't try `zeroclipr` but I am unsure about forcing my users to enable flash on their machines. I can try to provide information and be a guinea pig if there is enough impetus to spend time on this

I am on Shiny Server v1.5.6.875 and R 3.4.4

**Comment by phileas-condemine** [comment]
Same issue here on windows 10, the rclipbutton doesn't work within shiny modaldialog. I found this app that uses the class modal + some jquery with shinyjs. This way it works !
https://github.com/labsyspharm/smallmoleculesuite/blob/master/SelectivitySelectR/app.R
if you want to try it on the app : https://labsyspharm.shinyapps.io/selectivityselectr/

**Comment by sbihorel** [comment]
The problem appears to be with clipboard.js (ie, the underlying javascript library behind the rclipboard package) which has an issue with the bootstrap.js library used by shiny ([link to github issue](https://github.com/zenorocha/clipboard.js/issues/155)).

There are various workarounds that I am looking into...

**Comment by sbihorel** [comment]
@shinyquant, @oganm, @phileas-condemine:
The rclipButton function has been modified. The modal argument has been added and should be set to TRUE when the button is included in modal window
