### ISSUE TITLE
Encoding

### ISSUE THREAD

**Issue by thfuchs** [sbihorel/rclipboard#7]
Is there an option to switch encoding? E.g. German Umlaute are escaped when using your function. Could you add some functionality to also serve symbols and similar?

**Comment by sbihorel** [comment]
Hi,

I will need more context for this request, as I have zero problem copy pasting the following German unicode characters, üäöß, using the simple example app provided in the home page of [rclipboard](https://github.com/sbihorel/rclipboard).

Please provide a [reproducible example](https://community.rstudio.com/t/faq-whats-a-reproducible-example-reprex-and-how-do-i-do-one/5219)

**Comment by thfuchs** [comment]
I'm very sorry, think some unix misconfiguration lead to this, it's working now
